### ISSUE TITLE
Problems with Quick Start Guide

### ISSUE THREAD

**Issue by JoaoPFranca** [hyperledger/identus-edge-agent-sdk-kmp#167]
### Is this a regression?

Yes

### Description

Hello! I'm following the Quick Start Guide (https://docs.atalaprism.io/docs/quick-start/), but I have problems.
I'm using the cloud agent at my VM (10.0.2.15), the atala-prism common mediator and the Edge Agent SDK KMP.

I can connect to the mediator. But whenever I put the connection invite, I get an error.

### Please provide the exception or error you saw

```true
Process: org.hyperledger.identus.walletsdk, PID: 12171
                                                                                                    **org.didcommx.didcomm.exceptions.MalformedMessageException: Message cannot be parsed**
                                                                                                    	at org.didcommx.didcomm.operations.UnpackKt.unpack(Unpack.kt:31)
                                                                                                    	at org.didcommx.didcomm.DIDComm.unpack(DIDComm.kt:218)
                                                                                                    	at org.hyperledger.identus.walletsdk.mercury.resolvers.DIDCommWrapper.unpack(DIDCommWrapper.kt:267)
                                                                                                    	at org.hyperledger.identus.walletsdk.mercury.MercuryImpl.unpackMessage(MercuryImpl.kt:91)
                                                                                                    	at org.hyperledger.identus.walletsdk.mercury.MercuryImpl.sendMessageParseResponse(MercuryImpl.kt:187)
                                                                                                    	at org.hyperledger.identus.walletsdk.mercury.MercuryImpl$sendMessageParseResponse$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:149)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:11)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:66)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@993750a, Dispatchers.Main.immediate]
                                                                                                    **Caused by: java.text.ParseException: Invalid JSON: Unexpected token CLEARTEXT communication to 10.0.2.15 not permitted by network security policy at position 89.**
                                                                                                    	at com.nimbusds.jose.util.JSONObjectUtils.parse(JSONObjectUtils.java:111)
                                                                                                    	at com.nimbusds.jose.util.JSONObjectUtils.parse(JSONObjectUtils.java:69)
                                                                                                    	at org.didcommx.didcomm.operations.UnpackKt.unpack(Unpack.kt:24)
                                                                                                    	... 22 more
```

**Comment by mkbreuningIOHK** [comment]
@JoaoPFranca , as per Discord exchange on 28-Jun-2024 with @elribonazo , could you update the issue?

> You need to allow your ipaddress to the allowed list  https://stackoverflow.com/questions/60175852/cleartext-communication-not-permitted-by-network-security-policy-working-on-my-m

> Yes. I've followed the link sent here. It worked perfectly. Thanks!

**Comment by JoaoPFranca** [comment]
Of course! Thank you for the support, @elribonazo.
