### ISSUE TITLE
Crash was app after occurring error "Calling api result in 500 error"

### ISSUE THREAD

**Issue by kieutuan218** [hyperledger/identus-edge-agent-sdk-kmp#217]
### Is this a regression?

Yes

### Description

Sometime i got this error and app was crash.
I think we need catch exception when listen message from mediator

```
I/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Calling api result in 200 success
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Trying to resolve DID
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Metadata: 6a85985306225614573b263bbe39dc81c03475ab17c2a2525a246862443783c8
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Trying to resolve DID
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Metadata: 6a85985306225614573b263bbe39dc81c03475ab17c2a2525a246862443783c8
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Packing message https://didcomm.org/messagepickup/3.0/delivery-request
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Metadata: 16bffceccf48c11cfe63394aa8a94a2dd7217930055aa3ecc72e050db77c713e
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): , 6a85985306225614573b263bbe39dc81c03475ab17c2a2525a246862443783c8
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Trying to resolve DID
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Metadata: 6a85985306225614573b263bbe39dc81c03475ab17c2a2525a246862443783c8
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Trying to resolve DID
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Metadata: 16bffceccf48c11cfe63394aa8a94a2dd7217930055aa3ecc72e050db77c713e
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Trying to resolve DID
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.CASTOR]( 9342): Metadata: 6a85985306225614573b263bbe39dc81c03475ab17c2a2525a246862443783c8
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Sending message with type https://didcomm.org/messagepickup/3.0/delivery-request
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Metadata: 16bffceccf48c11cfe63394aa8a94a2dd7217930055aa3ecc72e050db77c713e
D/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): , 6a85985306225614573b263bbe39dc81c03475ab17c2a2525a246862443783c8
E/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Calling api result in 500 error
E/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): Metadata: 500
E/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): , https://mediator.infinect-did.xxx.net
E/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342): , ------
E/[org.hyperledger.identus.walletsdk.logger.LogComponent.MERCURY]( 9342):
E/AndroidRuntime( 9342): FATAL EXCEPTION: DefaultDispatcher-worker-11
E/AndroidRuntime( 9342): Process: com.example.holder_did, PID: 9342
E/AndroidRuntime( 9342): org.didcommx.didcomm.exceptions.MalformedMessageException: Message cannot be parsed
E/AndroidRuntime( 9342):        at org.didcommx.didcomm.operations.UnpackKt.unpack(Unpack.kt:31)
E/AndroidRuntime( 9342):        at org.didcommx.didcomm.DIDComm.unpack(DIDComm.kt:218)
E/AndroidRuntime( 9342):        at org.hyperledger.identus.walletsdk.mercury.resolvers.DIDCommWrapper.unpack(DIDCommWrapper.kt:266)
E/AndroidRuntime( 9342):        at org.hyperledger.identus.walletsdk.mercury.MercuryImpl.unpackMessage(MercuryImpl.kt:91)
E/AndroidRuntime( 9342):        at org.hyperledger.identus.walletsdk.mercury.MercuryImpl.sendMessageParseResponse(MercuryImpl.kt:187)
E/AndroidRuntime( 9342):        at org.hyperledger.identus.walletsdk.mercury.MercuryImpl$sendMessageParseResponse$1.invokeSuspend(Unknown Source:15)
E/AndroidRuntime( 9342):        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
E/AndroidRuntime( 9342):        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
E/AndroidRuntime( 9342):        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ef59ab6, Dispatchers.IO]
E/AndroidRuntime( 9342): Caused by: java.text.ParseException: Invalid JSON: Unexpected token Unable to resolve host "mediator.infinect-did.ekoios.net": No address associated with hostname at position 106.
E/AndroidRuntime( 9342):        at com.nimbusds.jose.util.JSONObjectUtils.parse(JSONObjectUtils.java:111)
E/AndroidRuntime( 9342):        at com.nimbusds.jose.util.JSONObjectUtils.parse(JSONObjectUtils.java:69)
E/AndroidRuntime( 9342):        at org.didcommx.didcomm.operations.UnpackKt.unpack(Unpack.kt:24)
E/AndroidRuntime( 9342):        ... 13 more
```

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in

```true

```

**Comment by yshyn-iohk** [comment]
Hi, @kieutuan218, my apologies for the delay.
From the logs, it looks like the application cannot resolve the mediator:
`Unable to resolve host "mediator.infinect-did.ekoios.net"`
Could it be the problems with your infrastructure?
Could you check the logs of your mediator instance as well?
